# Preprocessing and Feature Engineering

This notebook prepares the fraud detection dataset for model training.

Main steps:

1. Load raw dataset
2. Clean column names
3. Remove duplicate rows
4. Build engineered features
5. Inspect new features
6. Run full preprocessing pipeline
7. Save train/test processed files

In [1]:
import sys
from pathlib import Path

import pandas as pd

# Project root setup
PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.data.load_data import load_raw_data
from src.data.preprocess import (
    clean_column_names,
    remove_duplicates,
    run_preprocessing_pipeline,
)
from src.features.build_features import build_features

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.4f}".format)

In [2]:
df = load_raw_data()

df.head()

Data loaded successfully.
Rows: 6362620
Columns: 11

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.6400,C1231006815,170136.0000,160296.3600,M1979787155,0.0000,0.0000,0,0
1,1,PAYMENT,1864.2800,C1666544295,21249.0000,19384.7200,M2044282225,0.0000,0.0000,0,0
2,1,TRANSFER,181.0000,C1305486145,181.0000,0.0000,C553264065,0.0000,0.0000,1,0
3,1,CASH_OUT,181.0000,C840083671,181.0000,0.0000,C38997010,21182.0000,0.0000,1,0
4,1,PAYMENT,11668.1400,C2048537720,41554.0000,29885.8600,M1230701703,0.0000,0.0000,0,0

In [3]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 6362620
Columns: 11

In [4]:
df.columns.tolist()

['step',
 'type',
 'amount',
 'nameOrig',
 'oldbalanceOrg',
 'newbalanceOrig',
 'nameDest',
 'oldbalanceDest',
 'newbalanceDest',
 'isFraud',
 'isFlaggedFraud']

In [5]:
df = clean_column_names(df)

df.head()

,step,type,amount,name_orig,old_balance_orig,new_balance_orig,name_dest,old_balance_dest,new_balance_dest,is_fraud,is_flagged_fraud
0,1,PAYMENT,9839.6400,C1231006815,170136.0000,160296.3600,M1979787155,0.0000,0.0000,0,0
1,1,PAYMENT,1864.2800,C1666544295,21249.0000,19384.7200,M2044282225,0.0000,0.0000,0,0
2,1,TRANSFER,181.0000,C1305486145,181.0000,0.0000,C553264065,0.0000,0.0000,1,0
3,1,CASH_OUT,181.0000,C840083671,181.0000,0.0000,C38997010,21182.0000,0.0000,1,0
4,1,PAYMENT,11668.1400,C2048537720,41554.0000,29885.8600,M1230701703,0.0000,0.0000,0,0

In [6]:
df.columns.tolist()

['step',
 'type',
 'amount',
 'name_orig',
 'old_balance_orig',
 'new_balance_orig',
 'name_dest',
 'old_balance_dest',
 'new_balance_dest',
 'is_fraud',
 'is_flagged_fraud']

In [7]:
df = remove_duplicates(df)

df.shape

Duplicate rows removed: 0

(6362620, 11)

In [8]:
df["is_fraud"].value_counts()

is_fraud
0    6354407
1       8213
Name: count, dtype: int64

In [9]:
df["is_fraud"].value_counts(normalize=True) * 100

is_fraud
0   99.8709
1    0.1291
Name: proportion, dtype: float64

In [10]:
feature_df = build_features(df)

feature_df.head()

Feature engineering completed.
Total columns after feature engineering: 32

,step,type,amount,name_orig,old_balance_orig,new_balance_orig,name_dest,old_balance_dest,new_balance_dest,is_fraud,is_flagged_fraud,amount_log,amount_is_zero,amount_is_high,hour,day,is_night,day_of_week,is_weekend_simulated,is_cash_out,is_transfer,is_payment,is_debit,is_cash_in,origin_balance_diff,destination_balance_diff,origin_balance_error,destination_balance_error,origin_balance_ratio,destination_balance_ratio,origin_old_balance_is_zero,destination_old_balance_is_zero
0,1,PAYMENT,9839.6400,C1231006815,170136.0000,160296.3600,M1979787155,0.0000,0.0000,0,0,9.1943,0,0,1,0,1,0,0,0,0,1,0,0,9839.6400,0.0000,0.0000,9839.6400,0.0578,0.0000,0,1
1,1,PAYMENT,1864.2800,C1666544295,21249.0000,19384.7200,M2044282225,0.0000,0.0000,0,0,7.5312,0,0,1,0,1,0,0,0,0,1,0,0,1864.2800,0.0000,0.0000,1864.2800,0.0877,0.0000,0,1
2,1,TRANSFER,181.0000,C1305486145,181.0000,0.0000,C553264065,0.0000,0.0000,1,0,5.2040,0,0,1,0,1,0,0,0,1,0,0,0,181.0000,0.0000,0.0000,181.0000,1.0000,0.0000,0,1
3,1,CASH_OUT,181.0000,C840083671,181.0000,0.0000,C38997010,21182.0000,0.0000,1,0,5.2040,0,0,1,0,1,0,0,1,0,0,0,0,181.0000,-21182.0000,0.0000,21363.0000,1.0000,0.0085,0,0
4,1,PAYMENT,11668.1400,C2048537720,41554.0000,29885.8600,M1230701703,0.0000,0.0000,0,0,9.3647,0,0,1,0,1,0,0,0,0,1,0,0,11668.1400,0.0000,0.0000,11668.1400,0.2808,0.0000,0,1

In [11]:
feature_df.columns.tolist()

['step',
 'type',
 'amount',
 'name_orig',
 'old_balance_orig',
 'new_balance_orig',
 'name_dest',
 'old_balance_dest',
 'new_balance_dest',
 'is_fraud',
 'is_flagged_fraud',
 'amount_log',
 'amount_is_zero',
 'amount_is_high',
 'hour',
 'day',
 'is_night',
 'day_of_week',
 'is_weekend_simulated',
 'is_cash_out',
 'is_transfer',
 'is_payment',
 'is_debit',
 'is_cash_in',
 'origin_balance_diff',
 'destination_balance_diff',
 'origin_balance_error',
 'destination_balance_error',
 'origin_balance_ratio',
 'destination_balance_ratio',
 'origin_old_balance_is_zero',
 'destination_old_balance_is_zero']

In [12]:
new_columns = [
    "amount_log",
    "amount_is_zero",
    "amount_is_high",
    "hour",
    "day",
    "is_night",
    "day_of_week",
    "is_weekend_simulated",
    "is_cash_out",
    "is_transfer",
    "is_payment",
    "is_debit",
    "is_cash_in",
    "origin_balance_diff",
    "destination_balance_diff",
    "origin_balance_error",
    "destination_balance_error",
    "origin_balance_ratio",
    "destination_balance_ratio",
    "origin_old_balance_is_zero",
    "destination_old_balance_is_zero",
]

feature_df[new_columns].head()

,amount_log,amount_is_zero,amount_is_high,hour,day,is_night,day_of_week,is_weekend_simulated,is_cash_out,is_transfer,is_payment,is_debit,is_cash_in,origin_balance_diff,destination_balance_diff,origin_balance_error,destination_balance_error,origin_balance_ratio,destination_balance_ratio,origin_old_balance_is_zero,destination_old_balance_is_zero
0,9.1943,0,0,1,0,1,0,0,0,0,1,0,0,9839.6400,0.0000,0.0000,9839.6400,0.0578,0.0000,0,1
1,7.5312,0,0,1,0,1,0,0,0,0,1,0,0,1864.2800,0.0000,0.0000,1864.2800,0.0877,0.0000,0,1
2,5.2040,0,0,1,0,1,0,0,0,1,0,0,0,181.0000,0.0000,0.0000,181.0000,1.0000,0.0000,0,1
3,5.2040,0,0,1,0,1,0,0,1,0,0,0,0,181.0000,-21182.0000,0.0000,21363.0000,1.0000,0.0085,0,0
4,9.3647,0,0,1,0,1,0,0,0,0,1,0,0,11668.1400,0.0000,0.0000,11668.1400,0.2808,0.0000,0,1

In [13]:
feature_df.groupby("is_fraud")[
    [
        "amount_log",
        "origin_balance_diff",
        "destination_balance_diff",
        "origin_balance_ratio",
        "destination_balance_ratio",
        "is_transfer",
        "is_cash_out",
    ]
].mean()

,amount_log,origin_balance_diff,destination_balance_diff,origin_balance_ratio,destination_balance_ratio,is_transfer,is_cash_out
is_fraud,,,,,,,
0,10.8382,-23141.5164,123504.8100,81.8178,5.8998,0.0832,0.3515
1,12.8920,1457274.9739,735457.9981,0.9938,24.3566,0.4988,0.5012

In [14]:
feature_preview_path = PROJECT_ROOT / "reports" / "feature_engineering_preview.csv"

feature_df[
    [
        "step",
        "type",
        "amount",
        "amount_log",
        "hour",
        "day",
        "is_night",
        "is_transfer",
        "is_cash_out",
        "origin_balance_diff",
        "destination_balance_diff",
        "is_fraud",
    ]
].head(100).to_csv(feature_preview_path, index=False)

feature_preview_path

WindowsPath('c:/Users/User/Documents/fraud-detection-system/reports/feature_engineering_preview.csv')

## Feature Engineering Summary

In this step, new transaction-level features were created to improve model learning.

### Amount Features

- `amount_log`
- `amount_is_zero`
- `amount_is_high`

### Time Features

- `hour`
- `day`
- `day_of_week`
- `is_night`
- `is_weekend_simulated`

### Transaction Type Features

- `is_cash_out`
- `is_transfer`
- `is_payment`
- `is_debit`
- `is_cash_in`

### Balance Features

- `origin_balance_diff`
- `destination_balance_diff`
- `origin_balance_error`
- `destination_balance_error`
- `origin_balance_ratio`
- `destination_balance_ratio`
- `origin_old_balance_is_zero`
- `destination_old_balance_is_zero`

### Important Note

Some balance-based features may use post-transaction information.  
These features are useful for experimentation, but in a real-time fraud detection system they should be reviewed carefully to avoid data leakage.

In [15]:
X_train, X_test, y_train, y_test, preprocessor = run_preprocessing_pipeline()

Loading raw data...
Data loaded successfully.
Rows: 6362620
Columns: 11

Cleaning column names...

Removing duplicates...
Duplicate rows removed: 0

Building engineered features...
Feature engineering completed.
Total columns after feature engineering: 32

Preparing features and target...
Dropped columns: ['name_orig', 'name_dest', 'is_flagged_fraud']
Feature columns: ['step', 'type', 'amount', 'old_balance_orig', 'new_balance_orig', 'old_balance_dest', 'new_balance_dest', 'amount_log', 'amount_is_zero', 'amount_is_high', 'hour', 'day', 'is_night', 'day_of_week', 'is_weekend_simulated', 'is_cash_out', 'is_transfer', 'is_payment', 'is_debit', 'is_cash_in', 'origin_balance_diff', 'destination_balance_diff', 'origin_balance_error', 'destination_balance_error', 'origin_balance_ratio', 'destination_balance_ratio', 'origin_old_balance_is_zero', 'destination_old_balance_is_zero']
Target column: is_fraud

Creating train/test split...
X_train shape: (5090096, 28)
X_test shape: (1272524, 28)
y_train shape: (5090096,)
y_test shape: (1272524,)

Building preprocessor...
Categorical columns: ['type']
Numerical columns: ['step', 'amount', 'old_balance_orig', 'new_balance_orig', 'old_balance_dest', 'new_balance_dest', 'amount_log', 'amount_is_zero', 'amount_is_high', 'hour', 'day', 'is_night', 'day_of_week', 'is_weekend_simulated', 'is_cash_out', 'is_transfer', 'is_payment', 'is_debit', 'is_cash_in', 'origin_balance_diff', 'destination_balance_diff', 'origin_balance_error', 'destination_balance_error', 'origin_balance_ratio', 'destination_balance_ratio', 'origin_old_balance_is_zero', 'destination_old_balance_is_zero']

Fitting preprocessor on training data only...

Saving processed data...
Processed train/test files saved successfully.

Saving preprocessor...
Preprocessor saved to: C:\Users\User\Documents\fraud-detection-system\data\processed\preprocessor.pkl

Preprocessing completed successfully.

In [16]:
X_train.head()

,step,type,amount,old_balance_orig,new_balance_orig,old_balance_dest,new_balance_dest,amount_log,amount_is_zero,amount_is_high,hour,day,is_night,day_of_week,is_weekend_simulated,is_cash_out,is_transfer,is_payment,is_debit,is_cash_in,origin_balance_diff,destination_balance_diff,origin_balance_error,destination_balance_error,origin_balance_ratio,destination_balance_ratio,origin_old_balance_is_zero,destination_old_balance_is_zero
292779,15,PAYMENT,9914.7400,44248.0000,34333.2600,0.0000,0.0000,9.2019,0,0,15,0,0,0,0,0,0,1,0,0,9914.7400,0.0000,0.0000,9914.7400,0.2241,0.0000,0,1
499763,20,PAYMENT,6854.5300,0.0000,0.0000,0.0000,0.0000,8.8328,0,0,20,0,0,0,0,0,0,1,0,0,0.0000,0.0000,-6854.5300,6854.5300,0.0000,0.0000,1,1
2970411,231,CASH_OUT,361211.8000,0.0000,0.0000,489745.1600,850956.9500,12.7972,0,0,15,9,0,2,0,1,0,0,0,0,0.0000,361211.7900,-361211.8000,0.0100,0.0000,0.7376,1,0
3137549,236,PAYMENT,7083.5100,0.0000,0.0000,0.0000,0.0000,8.8657,0,0,20,9,0,2,0,0,0,1,0,0,0.0000,0.0000,-7083.5100,7083.5100,0.0000,0.0000,1,1
1500682,143,CASH_IN,218019.5100,13045685.5800,13263705.0900,2438123.9800,2220104.4700,12.2923,0,0,23,5,0,5,1,0,0,0,0,1,-218019.5100,-218019.5100,-436039.0200,436039.0200,0.0167,0.0894,0,0

In [17]:
X_train.columns.tolist()

['step',
 'type',
 'amount',
 'old_balance_orig',
 'new_balance_orig',
 'old_balance_dest',
 'new_balance_dest',
 'amount_log',
 'amount_is_zero',
 'amount_is_high',
 'hour',
 'day',
 'is_night',
 'day_of_week',
 'is_weekend_simulated',
 'is_cash_out',
 'is_transfer',
 'is_payment',
 'is_debit',
 'is_cash_in',
 'origin_balance_diff',
 'destination_balance_diff',
 'origin_balance_error',
 'destination_balance_error',
 'origin_balance_ratio',
 'destination_balance_ratio',
 'origin_old_balance_is_zero',
 'destination_old_balance_is_zero']

In [18]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (5090096, 28)
X_test shape: (1272524, 28)
y_train shape: (5090096,)
y_test shape: (1272524,)

In [19]:
print("Train target distribution:")
print(y_train.value_counts(normalize=True) * 100)

print("\nTest target distribution:")
print(y_test.value_counts(normalize=True) * 100)

Train target distribution:
is_fraud
0   99.8709
1    0.1291
Name: proportion, dtype: float64

Test target distribution:
is_fraud
0   99.8709
1    0.1291
Name: proportion, dtype: float64

In [20]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['step', 'amount', 'old_balance_orig',
                                  'new_balance_orig', 'old_balance_dest',
                                  'new_balance_dest', 'amount_log',
                                  'amount_is_zero', 'amount_is_high', 'hour',
                                  'day', 'is_night', 'day_of_week',
                                  'is_weekend_simulated', 'is_cash_out',
                                  'is_transfer', 'is_payment', 'is_debit',
                                  'is_cash_in', 'origin_balance_diff',
                                  'destination_balance_diff',
                                  'origin_balance_error',
                                  'destination_balance_error',
                                  'origin_balance_ratio',
                                  'destination_balance_ratio',
                                  'origin_old_balance_is_zero',
                                  'destination_old_balance_is_zero']),
                                ('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['type'])])

In [21]:
processed_dir = PROJECT_ROOT / "data" / "processed"

list(processed_dir.iterdir())

[WindowsPath('c:/Users/User/Documents/fraud-detection-system/data/processed/.gitkeep'),
 WindowsPath('c:/Users/User/Documents/fraud-detection-system/data/processed/preprocessor.pkl'),
 WindowsPath('c:/Users/User/Documents/fraud-detection-system/data/processed/X_test.csv'),
 WindowsPath('c:/Users/User/Documents/fraud-detection-system/data/processed/X_train.csv'),
 WindowsPath('c:/Users/User/Documents/fraud-detection-system/data/processed/y_test.csv'),
 WindowsPath('c:/Users/User/Documents/fraud-detection-system/data/processed/y_train.csv')]

In [22]:
X_train_saved = pd.read_csv(processed_dir / "X_train.csv")
X_test_saved = pd.read_csv(processed_dir / "X_test.csv")
y_train_saved = pd.read_csv(processed_dir / "y_train.csv")
y_test_saved = pd.read_csv(processed_dir / "y_test.csv")

print("Saved X_train:", X_train_saved.shape)
print("Saved X_test:", X_test_saved.shape)
print("Saved y_train:", y_train_saved.shape)
print("Saved y_test:", y_test_saved.shape)

Saved X_train: (5090096, 28)
Saved X_test: (1272524, 28)
Saved y_train: (5090096, 1)
Saved y_test: (1272524, 1)