# Model Training

This notebook trains classical machine learning models for fraud detection.

Models trained:

1. Logistic Regression
2. Random Forest
3. XGBoost
4. CatBoost
5. XGBoost with undersampled training data

The models are evaluated on the original untouched test set.

In [1]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from src.models.train_model import train_and_evaluate_models
from src.utils.config import REPORTS_DIR, TRAINED_MODEL_DIR

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.4f}".format)

In [2]:
results_df = train_and_evaluate_models()

results_df

Loading processed train/test data...
Loading preprocessor...

Creating stratified training sample for weighted models...
Training sample shape: (250000, 28)
Training sample target distribution:
is_fraud
0   99.8708
1    0.1292
Name: proportion, dtype: float64

Loading undersampled training data...
Undersampled training shape: (39420, 28)
Undersampled target distribution:
is_fraud
0   83.3333
1   16.6667
Name: proportion, dtype: float64

Transforming test data...

Building models...

Training model: logistic_regression_balanced

c:\Users\User\Documents\fraud-detection-system\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1457: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Evaluating model: logistic_regression_balanced
Saved model: C:\Users\User\Documents\fraud-detection-system\models\trained\logistic_regression_balanced.pkl
Metrics:
precision: 0.03067987050085698
recall: 0.9805234327449787
f1_score: 0.059498088748545785
roc_auc: 0.9944081757350737
pr_auc: 0.6226295102666264
true_negatives: 1219982
false_positives: 50899
false_negatives: 32
true_positives: 1611

Training model: random_forest_balanced
Evaluating model: random_forest_balanced
Saved model: C:\Users\User\Documents\fraud-detection-system\models\trained\random_forest_balanced.pkl
Metrics:
precision: 0.9975594874923734
recall: 0.9951308581862447
f1_score: 0.9963436928702011
roc_auc: 0.9986487694793027
pr_auc: 0.9975417832537191
true_negatives: 1270877
false_positives: 4
false_negatives: 8
true_positives: 1635

Training model: xgboost_weighted
Evaluating model: xgboost_weighted
Saved model: C:\Users\User\Documents\fraud-detection-system\models\trained\xgboost_weighted.pkl
Metrics:
precision: 0.9963459196102314
recall: 0.995739500912964
f1_score: 0.9960426179604261
roc_auc: 0.9983319087101972
pr_auc: 0.9964320109347169
true_negatives: 1270875
false_positives: 6
false_negatives: 7
true_positives: 1636

Training model: catboost_weighted
Evaluating model: catboost_weighted
Saved model: C:\Users\User\Documents\fraud-detection-system\models\trained\catboost_weighted.pkl
Metrics:
precision: 0.9933211900425015
recall: 0.995739500912964
f1_score: 0.9945288753799392
roc_auc: 0.99948722867607
pr_auc: 0.9971963389546904
true_negatives: 1270870
false_positives: 11
false_negatives: 7
true_positives: 1636

Training model: xgboost_undersampled
Evaluating model: xgboost_undersampled
Saved model: C:\Users\User\Documents\fraud-detection-system\models\trained\xgboost_undersampled.pkl
Metrics:
precision: 0.831728332488596
recall: 0.9987827145465612
f1_score: 0.9076327433628318
roc_auc: 0.9998699417989155
pr_auc: 0.998590524042695
true_negatives: 1270549
false_positives: 332
false_negatives: 2
true_positives: 1641

Best model based on PR-AUC: xgboost_undersampled
Saved model: C:\Users\User\Documents\fraud-detection-system\models\trained\best_model.pkl
Model comparison saved to: C:\Users\User\Documents\fraud-detection-system\reports\model_comparison.csv
Training summary saved to: C:\Users\User\Documents\fraud-detection-system\reports\training_summary.json

Model training completed successfully.

,model_name,training_rows,precision,recall,f1_score,roc_auc,pr_auc,true_negatives,false_positives,false_negatives,true_positives
4,xgboost_undersampled,39420,0.8317,0.9988,0.9076,0.9999,0.9986,1270549,332,2,1641
1,random_forest_balanced,250000,0.9976,0.9951,0.9963,0.9986,0.9975,1270877,4,8,1635
3,catboost_weighted,250000,0.9933,0.9957,0.9945,0.9995,0.9972,1270870,11,7,1636
2,xgboost_weighted,250000,0.9963,0.9957,0.9960,0.9983,0.9964,1270875,6,7,1636
0,logistic_regression_balanced,250000,0.0307,0.9805,0.0595,0.9944,0.6226,1219982,50899,32,1611

In [3]:
model_comparison_path = REPORTS_DIR / "model_comparison.csv"

model_comparison = pd.read_csv(model_comparison_path)

model_comparison

,model_name,training_rows,precision,recall,f1_score,roc_auc,pr_auc,true_negatives,false_positives,false_negatives,true_positives
0,xgboost_undersampled,39420,0.8317,0.9988,0.9076,0.9999,0.9986,1270549,332,2,1641
1,random_forest_balanced,250000,0.9976,0.9951,0.9963,0.9986,0.9975,1270877,4,8,1635
2,catboost_weighted,250000,0.9933,0.9957,0.9945,0.9995,0.9972,1270870,11,7,1636
3,xgboost_weighted,250000,0.9963,0.9957,0.9960,0.9983,0.9964,1270875,6,7,1636
4,logistic_regression_balanced,250000,0.0307,0.9805,0.0595,0.9944,0.6226,1219982,50899,32,1611

In [4]:
model_comparison.sort_values(by="pr_auc", ascending=False)

,model_name,training_rows,precision,recall,f1_score,roc_auc,pr_auc,true_negatives,false_positives,false_negatives,true_positives
0,xgboost_undersampled,39420,0.8317,0.9988,0.9076,0.9999,0.9986,1270549,332,2,1641
1,random_forest_balanced,250000,0.9976,0.9951,0.9963,0.9986,0.9975,1270877,4,8,1635
2,catboost_weighted,250000,0.9933,0.9957,0.9945,0.9995,0.9972,1270870,11,7,1636
3,xgboost_weighted,250000,0.9963,0.9957,0.9960,0.9983,0.9964,1270875,6,7,1636
4,logistic_regression_balanced,250000,0.0307,0.9805,0.0595,0.9944,0.6226,1219982,50899,32,1611

In [5]:
model_comparison.sort_values(by="recall", ascending=False)

,model_name,training_rows,precision,recall,f1_score,roc_auc,pr_auc,true_negatives,false_positives,false_negatives,true_positives
0,xgboost_undersampled,39420,0.8317,0.9988,0.9076,0.9999,0.9986,1270549,332,2,1641
2,catboost_weighted,250000,0.9933,0.9957,0.9945,0.9995,0.9972,1270870,11,7,1636
3,xgboost_weighted,250000,0.9963,0.9957,0.9960,0.9983,0.9964,1270875,6,7,1636
1,random_forest_balanced,250000,0.9976,0.9951,0.9963,0.9986,0.9975,1270877,4,8,1635
4,logistic_regression_balanced,250000,0.0307,0.9805,0.0595,0.9944,0.6226,1219982,50899,32,1611

In [6]:
model_comparison.sort_values(by="f1_score", ascending=False)

,model_name,training_rows,precision,recall,f1_score,roc_auc,pr_auc,true_negatives,false_positives,false_negatives,true_positives
1,random_forest_balanced,250000,0.9976,0.9951,0.9963,0.9986,0.9975,1270877,4,8,1635
3,xgboost_weighted,250000,0.9963,0.9957,0.9960,0.9983,0.9964,1270875,6,7,1636
2,catboost_weighted,250000,0.9933,0.9957,0.9945,0.9995,0.9972,1270870,11,7,1636
0,xgboost_undersampled,39420,0.8317,0.9988,0.9076,0.9999,0.9986,1270549,332,2,1641
4,logistic_regression_balanced,250000,0.0307,0.9805,0.0595,0.9944,0.6226,1219982,50899,32,1611

In [7]:
list(TRAINED_MODEL_DIR.iterdir())

[WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/.gitkeep'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/best_model.pkl'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/catboost_weighted.pkl'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/logistic_regression_balanced.pkl'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/random_forest_balanced.pkl'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/xgboost_undersampled.pkl'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/models/trained/xgboost_weighted.pkl')]

## Model Training Notes

The trained models were evaluated using fraud-focused metrics instead of accuracy.

Important metrics:

- Precision
- Recall
- F1-score
- ROC-AUC
- PR-AUC
- Confusion matrix values

### Why PR-AUC is important

Fraud datasets are highly imbalanced. PR-AUC is more useful than accuracy because it focuses on how well the model finds the minority fraud class.

### Why recall is important

Recall shows how many real fraud transactions were correctly detected.

### Why precision is important

Precision shows how many predicted fraud transactions were actually fraud.

### Important Rule

The test set was not resampled.  
Only training data was sampled or class-weighted.