# Threshold Tuning

This notebook tests multiple fraud probability thresholds.

The goal is to find a better fraud decision threshold than the default `0.5`.

Threshold tuning helps balance:

- Precision
- Recall
- F1-score
- False positives
- False negatives

In [6]:
import sys
from pathlib import Path

import pandas as pd

# Robust project root finder
current_path = Path.cwd().resolve()

PROJECT_ROOT = current_path

while PROJECT_ROOT != PROJECT_ROOT.parent:
    if (PROJECT_ROOT / "src").exists() and (PROJECT_ROOT / "data").exists():
        break
    PROJECT_ROOT = PROJECT_ROOT.parent

if not ((PROJECT_ROOT / "src").exists() and (PROJECT_ROOT / "data").exists()):
    raise RuntimeError(
        "Could not find project root. Please open Jupyter from the fraud-detection-system folder."
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Current path:", current_path)
print("Project root:", PROJECT_ROOT)
print("src exists:", (PROJECT_ROOT / "src").exists())
print("data exists:", (PROJECT_ROOT / "data").exists())

from src.evaluation.threshold_tuning import run_threshold_tuning
from src.utils.config import REPORTS_DIR, FIGURES_DIR

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.6f}".format)

Current path: C:\Users\User\Documents\fraud-detection-system\src\models
Project root: C:\Users\User\Documents\fraud-detection-system
src exists: True
data exists: True

In [7]:
threshold_results, best_threshold_row = run_threshold_tuning()

Loading processed test data...
Loading preprocessor...
Loading best model...
Loading training summary...
Transforming test data...
Getting fraud probabilities...
Evaluating thresholds...
Selecting best threshold...

Best threshold:
threshold                   0.950000
precision                   0.941413
recall                      0.997565
f1_score                    0.968676
true_negatives        1270779.000000
false_positives           102.000000
false_negatives             4.000000
true_positives           1639.000000
false_positive_rate         0.000080
false_negative_rate         0.002435
Name: 18, dtype: float64

Creating plots...
Saved threshold metrics plot: C:\Users\User\Documents\fraud-detection-system\reports\figures\threshold_precision_recall_f1.png
Saved threshold confusion values plot: C:\Users\User\Documents\fraud-detection-system\reports\figures\threshold_confusion_values.png

Saving outputs...
Threshold tuning results saved to: C:\Users\User\Documents\fraud-detection-system\reports\threshold_tuning_results.csv
Threshold tuning summary saved to: C:\Users\User\Documents\fraud-detection-system\reports\threshold_tuning_summary.json
Model metadata saved to: C:\Users\User\Documents\fraud-detection-system\models\trained\model_metadata.json

Creating threshold report...
Threshold tuning report saved to: C:\Users\User\Documents\fraud-detection-system\reports\threshold_tuning_report.md

Threshold tuning completed successfully.

In [8]:
threshold_results

,threshold,precision,recall,f1_score,true_negatives,false_positives,false_negatives,true_positives,false_positive_rate,false_negative_rate
0,0.050000,0.680913,0.998783,0.809771,1270112,769,2,1641,0.000605,0.001217
1,0.100000,0.750000,0.998783,0.856695,1270334,547,2,1641,0.000430,0.001217
2,0.150000,0.772235,0.998783,0.871019,1270397,484,2,1641,0.000381,0.001217
3,0.200000,0.786296,0.998783,0.879893,1270435,446,2,1641,0.000351,0.001217
4,0.250000,0.798540,0.998783,0.887507,1270467,414,2,1641,0.000326,0.001217
5,0.300000,0.805201,0.998783,0.891606,1270484,397,2,1641,0.000312,0.001217
6,0.350000,0.813585,0.998783,0.896721,1270505,376,2,1641,0.000296,0.001217
7,0.400000,0.821321,0.998783,0.901401,1270524,357,2,1641,0.000281,0.001217
8,0.450000,0.827117,0.998783,0.904880,1270538,343,2,1641,0.000270,0.001217
9,0.500000,0.831728,0.998783,0.907633,1270549,332,2,1641,0.000261,0.001217
10,0.550000,0.836391,0.998783,0.910402,1270560,321,2,1641,0.000253,0.001217
11,0.600000,0.843268,0.998783,0.914461,1270576,305,2,1641,0.000240,0.001217
12,0.650000,0.848062,0.998783,0.917272,1270587,294,2,1641,0.000231,0.001217
13,0.700000,0.853722,0.998174,0.920314,1270600,281,3,1640,0.000221,0.001826
14,0.750000,0.861345,0.998174,0.924725,1270617,264,3,1640,0.000208,0.001826
15,0.800000,0.874667,0.998174,0.932348,1270646,235,3,1640,0.000185,0.001826
16,0.850000,0.889853,0.998174,0.940906,1270678,203,3,1640,0.000160,0.001826
17,0.900000,0.907028,0.997565,0.950145,1270713,168,4,1639,0.000132,0.002435
18,0.950000,0.941413,0.997565,0.968676,1270779,102,4,1639,0.000080,0.002435

In [9]:
threshold_results.sort_values(by="f1_score", ascending=False)

,threshold,precision,recall,f1_score,true_negatives,false_positives,false_negatives,true_positives,false_positive_rate,false_negative_rate
18,0.950000,0.941413,0.997565,0.968676,1270779,102,4,1639,0.000080,0.002435
17,0.900000,0.907028,0.997565,0.950145,1270713,168,4,1639,0.000132,0.002435
16,0.850000,0.889853,0.998174,0.940906,1270678,203,3,1640,0.000160,0.001826
15,0.800000,0.874667,0.998174,0.932348,1270646,235,3,1640,0.000185,0.001826
14,0.750000,0.861345,0.998174,0.924725,1270617,264,3,1640,0.000208,0.001826
13,0.700000,0.853722,0.998174,0.920314,1270600,281,3,1640,0.000221,0.001826
12,0.650000,0.848062,0.998783,0.917272,1270587,294,2,1641,0.000231,0.001217
11,0.600000,0.843268,0.998783,0.914461,1270576,305,2,1641,0.000240,0.001217
10,0.550000,0.836391,0.998783,0.910402,1270560,321,2,1641,0.000253,0.001217
9,0.500000,0.831728,0.998783,0.907633,1270549,332,2,1641,0.000261,0.001217
8,0.450000,0.827117,0.998783,0.904880,1270538,343,2,1641,0.000270,0.001217
7,0.400000,0.821321,0.998783,0.901401,1270524,357,2,1641,0.000281,0.001217
6,0.350000,0.813585,0.998783,0.896721,1270505,376,2,1641,0.000296,0.001217
5,0.300000,0.805201,0.998783,0.891606,1270484,397,2,1641,0.000312,0.001217
4,0.250000,0.798540,0.998783,0.887507,1270467,414,2,1641,0.000326,0.001217
3,0.200000,0.786296,0.998783,0.879893,1270435,446,2,1641,0.000351,0.001217
2,0.150000,0.772235,0.998783,0.871019,1270397,484,2,1641,0.000381,0.001217
1,0.100000,0.750000,0.998783,0.856695,1270334,547,2,1641,0.000430,0.001217
0,0.050000,0.680913,0.998783,0.809771,1270112,769,2,1641,0.000605,0.001217

In [10]:
threshold_results.sort_values(by="precision", ascending=False)

,threshold,precision,recall,f1_score,true_negatives,false_positives,false_negatives,true_positives,false_positive_rate,false_negative_rate
18,0.950000,0.941413,0.997565,0.968676,1270779,102,4,1639,0.000080,0.002435
17,0.900000,0.907028,0.997565,0.950145,1270713,168,4,1639,0.000132,0.002435
16,0.850000,0.889853,0.998174,0.940906,1270678,203,3,1640,0.000160,0.001826
15,0.800000,0.874667,0.998174,0.932348,1270646,235,3,1640,0.000185,0.001826
14,0.750000,0.861345,0.998174,0.924725,1270617,264,3,1640,0.000208,0.001826
13,0.700000,0.853722,0.998174,0.920314,1270600,281,3,1640,0.000221,0.001826
12,0.650000,0.848062,0.998783,0.917272,1270587,294,2,1641,0.000231,0.001217
11,0.600000,0.843268,0.998783,0.914461,1270576,305,2,1641,0.000240,0.001217
10,0.550000,0.836391,0.998783,0.910402,1270560,321,2,1641,0.000253,0.001217
9,0.500000,0.831728,0.998783,0.907633,1270549,332,2,1641,0.000261,0.001217
8,0.450000,0.827117,0.998783,0.904880,1270538,343,2,1641,0.000270,0.001217
7,0.400000,0.821321,0.998783,0.901401,1270524,357,2,1641,0.000281,0.001217
6,0.350000,0.813585,0.998783,0.896721,1270505,376,2,1641,0.000296,0.001217
5,0.300000,0.805201,0.998783,0.891606,1270484,397,2,1641,0.000312,0.001217
4,0.250000,0.798540,0.998783,0.887507,1270467,414,2,1641,0.000326,0.001217
3,0.200000,0.786296,0.998783,0.879893,1270435,446,2,1641,0.000351,0.001217
2,0.150000,0.772235,0.998783,0.871019,1270397,484,2,1641,0.000381,0.001217
1,0.100000,0.750000,0.998783,0.856695,1270334,547,2,1641,0.000430,0.001217
0,0.050000,0.680913,0.998783,0.809771,1270112,769,2,1641,0.000605,0.001217

In [11]:
best_threshold_row

threshold                   0.950000
precision                   0.941413
recall                      0.997565
f1_score                    0.968676
true_negatives        1270779.000000
false_positives           102.000000
false_negatives             4.000000
true_positives           1639.000000
false_positive_rate         0.000080
false_negative_rate         0.002435
Name: 18, dtype: float64

In [12]:
summary_path = REPORTS_DIR / "threshold_tuning_summary.json"

print(summary_path.read_text(encoding="utf-8"))

{
    "best_model": "xgboost_undersampled",
    "selection_metric": "f1_score",
    "selected_threshold": 0.9500000000000001,
    "precision": 0.9414129810453762,
    "recall": 0.9975654290931223,
    "f1_score": 0.9686761229314421,
    "true_negatives": 1270779,
    "false_positives": 102,
    "false_negatives": 4,
    "true_positives": 1639,
    "notes": [
        "The default threshold 0.5 is not always optimal for fraud detection.",
        "This selected threshold maximizes F1-score as a balanced starting point.",
        "In a real bank, the final threshold should be selected based on fraud cost, false positive cost, and analyst review capacity."
    ]
}

In [13]:
report_path = REPORTS_DIR / "threshold_tuning_report.md"

print(report_path.read_text(encoding="utf-8"))

# Threshold Tuning Report

## Project

End-to-End Fraud Detection System

## Version

Version 1 — Classical Machine Learning Fraud Detection

---

## Goal

The goal of threshold tuning is to find a better fraud decision threshold instead of using the default threshold of `0.5`.

Fraud detection is highly imbalanced, so the default threshold may not give the best balance between fraud detection and false alarms.

---

## Best Model

`xgboost_undersampled`

---

## Selected Threshold

`0.95`

This threshold was selected based on the highest F1-score.

---

## Metrics at Selected Threshold

| Metric | Value |
|---|---:|
| Precision | 0.941413 |
| Recall | 0.997565 |
| F1-score | 0.968676 |
| True Negatives | 1270779 |
| False Positives | 102 |
| False Negatives | 4 |
| True Positives | 1639 |

---

## Top Thresholds by F1-score

|   threshold |   precision |   recall |   f1_score |   true_negatives |   false_positives |   false_negatives |   true_positives |   false_positive_rate |   false_negative_rate |
|------------:|------------:|---------:|-----------:|-----------------:|------------------:|------------------:|-----------------:|----------------------:|----------------------:|
|        0.95 |    0.941413 | 0.997565 |   0.968676 |      1.27078e+06 |               102 |                 4 |             1639 |           8.02593e-05 |            0.00243457 |
|        0.9  |    0.907028 | 0.997565 |   0.950145 |      1.27071e+06 |               168 |                 4 |             1639 |           0.000132192 |            0.00243457 |
|        0.85 |    0.889853 | 0.998174 |   0.940906 |      1.27068e+06 |               203 |                 3 |             1640 |           0.000159732 |            0.00182593 |
|        0.8  |    0.874667 | 0.998174 |   0.932348 |      1.27065e+06 |               235 |                 3 |             1640 |           0.000184911 |            0.00182593 |
|        0.75 |    0.861345 | 0.998174 |   0.924725 |      1.27062e+06 |               264 |                 3 |             1640 |           0.00020773  |            0.00182593 |
|        0.7  |    0.853722 | 0.998174 |   0.920314 |      1.2706e+06  |               281 |                 3 |             1640 |           0.000221106 |            0.00182593 |
|        0.65 |    0.848062 | 0.998783 |   0.917272 |      1.27059e+06 |               294 |                 2 |             1641 |           0.000231336 |            0.00121729 |
|        0.6  |    0.843268 | 0.998783 |   0.914461 |      1.27058e+06 |               305 |                 2 |             1641 |           0.000239991 |            0.00121729 |
|        0.55 |    0.836391 | 0.998783 |   0.910402 |      1.27056e+06 |               321 |                 2 |             1641 |           0.000252581 |            0.00121729 |
|        0.5  |    0.831728 | 0.998783 |   0.907633 |      1.27055e+06 |               332 |                 2 |             1641 |           0.000261236 |            0.00121729 |

---

## Generated Figures

- `reports/figures/threshold_precision_recall_f1.png`
- `reports/figures/threshold_confusion_values.png`

---

## Interpretation

Lower thresholds usually increase recall, meaning more fraud cases are detected.

However, lower thresholds can also increase false positives, meaning more legitimate transactions are flagged as fraud.

Higher thresholds usually reduce false positives but may miss more fraud cases.

The selected threshold is a balanced starting point. In a real banking system, the final threshold should be selected based on business cost, analyst review capacity, and customer impact.

---

## Next Step

Step 10 — SHAP Explainability

In [14]:
list(FIGURES_DIR.iterdir())

[WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/.gitkeep'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/amount_distribution_log.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/amount_fraud_vs_nonfraud.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/confusion_matrix_best_model.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/correlation_heatmap.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/fraud_by_transaction_type.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/fraud_over_time_steps.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/fraud_rate_over_time_steps.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/model_comparison_pr_auc.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/model_comparison_recall.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/precision_recall_curve_best_model.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/roc_curve_best_model.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/target_distribution.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/threshold_confusion_values.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/threshold_precision_recall_f1.png'),
 WindowsPath('C:/Users/User/Documents/fraud-detection-system/reports/figures/transaction_type_distribution.png')]

## Threshold Tuning Notes

The default threshold of `0.5` may not be optimal for fraud detection.

### Lower Threshold

A lower threshold usually catches more fraud cases.

Benefit:

- Higher recall

Risk:

- More false positives

### Higher Threshold

A higher threshold usually reduces false alarms.

Benefit:

- Higher precision

Risk:

- More false negatives

### Selected Threshold

The selected threshold in this experiment is based on the highest F1-score.

In a real banking system, the final threshold should be selected based on:

- Cost of missed fraud
- Cost of false alarms
- Analyst review capacity
- Customer experience